### ISSUE TITLE
Taxonomies not filtered when creating a new post/page

### ISSUE THREAD

**Issue by Htbaa** [Sladix/Restrict-Taxonomies#1]
Hi,

just checked out your plugin but the displayed taxonomies are not filtered when creating a new post or page. Editing an existing one filters the taxonomies just fine.

I found another plugin which seems to do the same as yours and also has the same problem. I fixed that in https://github.com/Htbaa/wordpress-restrict-taxonomies by making sure the filter is executed on 'post.php' and 'post-new.php'. Maybe your plugin has the same issue?

**Comment by Sladix** [comment]
Hi,

Are you sure ? What version of Wordpress are you using ? If you look at the code, the categories are filtered when creating a new post (line 687-694).

Maybe you did not checked the taxonomy or the post type in the "Post types and Taxonomy Settings" ?

I just tested it and it works fine for me (wp 4.3.1)

**Comment by Htbaa** [comment]
I'm on 4.3.1 as well. But I just noticed there's a new update of your plugin. Will try that first.

**Comment by Htbaa** [comment]
Just confirmed it. It works for posts, but not for pages.

**Comment by Sladix** [comment]
It was not initially planned that it works for pages but I'm going to add this asap.

(are page taxonomies a vanilla wordpress thing ?)

**Comment by Htbaa** [comment]
Yeah they are. Posts and pages are more or less the same anyway. You can create taxonomies for pages, posts and custom post types. It's available in core WordPress.

**Comment by Sladix** [comment]
Oh ok, but in the default configuration there are no page taxonomies right ? or am I blind ?

I added the page taxonomies support (but the page post type doesn't not appear in the settings)

**Comment by Sladix** [comment]
Would you mind saying if it works or not ?
https://wordpress.org/plugins/restrict-taxonomies/
Thanks =)

**Comment by Htbaa** [comment]
That seems to work, yes. Thanks :+1:
