### ISSUE TITLE
Active support - WP plugin ?

### ISSUE THREAD

**Issue by buildpress** [Sladix/Restrict-Taxonomies#2]
Hi,

I cam across this project as i was searching for a way to restrict woocommerce categories.
I am wondering why you are not making it a genuine wordpress plugin ?

Jasper

**Comment by Sladix** [comment]
It is, on the wordpress.org repo =)

**Comment by buildpress** [comment]
Ah oke nice. How is it called ?

**Comment by Sladix** [comment]
@joomapp Sorry for the late answer,  here is the link : https://wordpress.org/plugins/restrict-taxonomies/

**Comment by buildpress** [comment]
thnx
