### ISSUE TITLE
Settings: Panel 'Users' does not load when you have too many users

### ISSUE THREAD

**Issue by andrenakazato** [Sladix/Restrict-Taxonomies#8]
I have the following problem: 
- The site I manage has around 20.000 users
- When I click on Settings > Restrict Taxonomies, tab 'Users', it loads slowly and when "finished", it does not show anything.
- Shows no error on PHP or SQL.

![image](https://cloud.githubusercontent.com/assets/5948306/23228457/52a7e730-f91b-11e6-875e-b56c1846f843.png)

If needed, we can provide you an enviroment with these users (because it is a lot).

**Comment by andrenakazato** [comment]
@Sladix Any update on this issue?

**Comment by andrenakazato** [comment]
@Sladix Hello, any update on this issue?

**Comment by Sladix** [comment]
Hi there,

@andrenakazato I'm sorry I won't have the time to look at this issue anytime soon

**Comment by cesf** [comment]
@andrenakazato Did you manage to solve this? We're experiencing it and we have 5k+ customers.

**Comment by Sladix** [comment]
A fix has been publish in order to tackle down this issue. Please open a new issue if the same problem persist.
